application: just-once
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /
  static_files: public/index.html
  upload: public/index.html

- url: /(.+)
  script: justonce.app

libraries:
- name: jinja2
  version: 2.6
