application: just-once
version: 1
runtime: python27
api_version: 1
threadsafe: true

inbound_services:
- warmup

handlers:
- url: /static
  static_dir: static

- url: /
  script: justonce.app

- url: /download/(.+)
  script: justonce.app

- url: /upload
  script: justonce.app

libraries:
- name: jinja2
  version: 2.6
